### ISSUE TITLE
about the other language client

### ISSUE THREAD

**Issue by zmwwxa** [ketho-wow/ClickMorph#1]
first of all,thx for ur hardworking,the addon is amazing.
when i use it in zhCN Client,when i alt+click,i got this:
ClickMorph: Could not find any morpher!
i think it might be cuased by the diffirent language.and i can offer u a translate list,if u can fix it.but i dont know the list that i should offer u 
I am looking forward to your reply

**Comment by Ketho** [comment]
你好，我是华人可是中文不好所以我跟你说英文
There is no localization yet, but ClickMorph should work on any client, including zhCN
https://github.com/ketho-wow/ClickMorph/blob/master/ClickMorph.lua#L48-L59

Are you sure you properly injected iMorph?
![image](https://user-images.githubusercontent.com/1073877/64922632-a81b2a00-d7d1-11e9-83ae-abfea1c8e3bd.png)
![image](https://user-images.githubusercontent.com/1073877/64922608-67231580-d7d1-11e9-9d84-420386611957.png)

**Comment by zmwwxa** [comment]
oh it also need imorph,okay,i almost think it is a Standalone addons.And it works now.ty
