### ISSUE TITLE
Hello, plugin author. I have an awkward request.

### ISSUE THREAD

**Issue by kuding-ye** [ketho-wow/ClickMorph#10]
I am playing World of Warcraft: Wrath of the Lich King classic version, and I have come across the fact that friends who are playing World of Warcraft: Classic are using your "ClickMorph" addon. However, the Dragon Era version addon and Burning Crusade classic version addon that I added to the Wrath of the Lich King classic version addon cannot run. Since I know you are posting here, I have specifically registered an account to make this request. If you have the time, I hope you can adapt an addon for the Wrath of the Lich King classic version. Thank you very much.

**Comment by Ketho** [comment]
I've stopped developing ClickMorph and can't test this on Classic Wrath, sorry 🙇

**Comment by kuding-ye** [comment]
Although it is regrettable that ClickMorph will no longer be updated, I am still very grateful for the convenience it has brought to World of Warcraft players. And I would also like to add that I truly appreciate the effort you put into developing it.
