### ISSUE TITLE
Doesn't support Titan's Grip (2H Dual Wield)

### ISSUE THREAD

**Issue by willgk** [ketho-wow/ClickMorph#2]
Would be lovely if we could get this supporting TItan's Grip spellid 46917, not sure how you could differentiate unless you can tell the difference between left click and right click and do mainhand left, offhand right?

**Comment by Ketho** [comment]
Yeah I didn't really support retail, it should be fixed now in [1.4.8](https://github.com/ketho-wow/ClickMorph/releases/tag/1.4.8)

It's possible to tell the difference between left and right click, but currently it just alternates between mainhand and offhand

**Comment by Ketho** [comment]
The 1.4.8 release didn't get packaged properly, for some reason it didn't pull a submodule (StdUi). I'll have to make a later release without using github actions

**Edit:** It should work now
https://github.com/ketho-wow/ClickMorph/releases/tag/1.5.0
