### ISSUE TITLE
Morphing offhand still not working with Titan's Grip.

### ISSUE THREAD

**Issue by willgk** [ketho-wow/ClickMorph#3]
I really hate to be a bother, Your addon is wonderful, however even after adding the Titan's Grip spell there's no way to actually use it to morph your offhand.

This may be because the unlocker doesn't properly put all of the different types of items in the offhand Appearance tab, though even on ones it does put in offhand it isn't recognizing that i'm in the offhand say if i try it on a fist weapon it still forces it to the mainhand.

If i'm just using this incorrectly can you let me know? Using jMorph if it matters, again thank you very very much.

**Comment by Ketho** [comment]
Oh I didn't really support the Appearances tab in retail with dualwielding, nothing to do with the unlocker. Can you try if it works in 1.5.2?

Note that it conflicts with jMorph code since they copied old ClickMorph code so e.g. when ClickMorph alternates morphing offhand, jMorph will at the same time morph mainhand slot

**Comment by willgk** [comment]
It now morphs offhand properly, however is the unlocker supposed to unlock all of the things that can display in offhand? I only have fists, shields, warglaives, instead of all of the weapons that shows in mainhand?

**Comment by Ketho** [comment]
I also didn't think of that when unlocking [C_TransmogCollection.GetCategoryInfo](https://wow.gamepedia.com/API_C_TransmogCollection.GetCategoryInfo)() but apparently what shows up in the offhand dropdown is different between classes. I'll have to look at it again some time

https://github.com/ketho-wow/ClickMorph/blob/1.5.2/Live/Wardrobe.lua#L34

**Comment by Ketho** [comment]
I'm not even sure if it should unlock everything in the offhand dropdown, I opted to just make it use the original values. Try [1.5.3-beta1](https://github.com/ketho-wow/ClickMorph/releases/tag/1.5.3-beta1)

**Comment by willgk** [comment]
Ok for some reason all of a sudden now when i alt click twice the first time it does mainhand the second time offhand (which is what i was after all along :D). This is after setting those items i wanted to true in the wardrobe.

So all is good now! Thank you
