### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by YungGodChris** [ketho-wow/ClickMorph#4]
Not really a big problem or anything just found no way to keep click morph from spamming my chat with the pieces I put on. Was wondering if there was a way

**Comment by Ketho** [comment]
Not currently no but I can add an option for silent mode

**Comment by YungGodChris** [comment]
If you could that would be very appreciated. Love the program and appreciate all the work you do

**Comment by Ketho** [comment]
Added a silent mode option in [1.5.6](https://github.com/ketho-wow/ClickMorph/releases/tag/1.5.6)
