### ISSUE TITLE
Alt click not working

### ISSUE THREAD

**Issue by YungGodChris** [ketho-wow/ClickMorph#5]
Alt clicking on appearances doesn't change my morph even with jmorph linked.

**Comment by Ketho** [comment]
Oh I didn't know jmorph was updated for 9.0.1, will have to take a look

**Comment by Ketho** [comment]
Should be fixed in https://github.com/ketho-wow/ClickMorph/releases/tag/1.7.0

btw jMorph actually incorporates clickmorph code so for the wardrobe it already is morphing without clickmorph
