### ISSUE TITLE
Incorrect parameter(1) type [int expected for slotId]

### ISSUE THREAD

**Issue by Toxiyk** [ketho-wow/ClickMorph#8]
Shadowlands patch 9.2.7, when trying to clickmorph a set as shown in the video, I get the error: 
Incorrect parameter(1) type [int expected for slotId]
I also cannot clickmorph any weapon enchants, and I can only clickmorph normal mode items.

**Comment by Ketho** [comment]
Oh, it probably needs an integer instead of a string, like `1` instead of `"HEADSLOT"`

But you will have to contact the developer of jMorph for 9.2.7 since clickmorph is no longer in development and jMorph might have changed their API in the meantime
