### ISSUE TITLE
LUA Errors in Dragonflight

### ISSUE THREAD

**Issue by ghost** [ketho-wow/ClickMorph#9]
Getting 2 errors when using the addon in 10.0.2 (Dragonflight)

> Message: Interface/AddOns/ClickMorph/Live/Mount.lua:30: attempt to index field 'ListScrollFrame' (a nil value)
> Time: Wed Dec 21 14:34:21 2022
> Count: 1
> Stack: Interface/AddOns/ClickMorph/Live/Mount.lua:30: attempt to index field 'ListScrollFrame' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface/AddOns/ClickMorph/Live/Mount.lua"]:30: in function <Interface/AddOns/ClickMorph/Live/Mount.lua:21>
> [string "=[C]"]: ?
> [string "=[C]"]: in function `Show'
> [string "@Interface/FrameXML/UIParent.lua"]:2890: in function `SetUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:2733: in function `ShowUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:2598: in function <Interface/FrameXML/UIParent.lua:2594>
> [string "=[C]"]: in function `SetAttribute'
> [string "@Interface/FrameXML/UIParent.lua"]:3196: in function `ShowUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:1195: in function `SetCollectionsJournalShown'
> [string "@Interface/FrameXML/UIParent.lua"]:1185: in function <Interface/FrameXML/UIParent.lua:1175>
> [string "=[C]"]: ?
> [string "=[C]"]: in function `ToggleCollectionsJournal'
> [string "TOGGLECOLLECTIONS"]:1: in function <[string "TOGGLECOLLECTIONS"]:1>
> 
> Locals: 

and

> Message: Interface/AddOns/ClickMorph/Live/Wardrobe.lua:202: attempt to call field 'GetIllusionSourceInfo' (a nil value)
> Time: Wed Dec 21 14:34:47 2022
> Count: 1
> Stack: Interface/AddOns/ClickMorph/Live/Wardrobe.lua:202: attempt to call field 'GetIllusionSourceInfo' (a nil value)
> [string "=[C]"]: in function `GetIllusionSourceInfo'
> [string "@Interface/AddOns/ClickMorph/Live/Wardrobe.lua"]:202: in function `QueryData'
> [string "@Interface/AddOns/ClickMorph/Live/Wardrobe.lua"]:159: in function `InitializeData'
> [string "@Interface/AddOns/ClickMorph/Live/Wardrobe.lua"]:143: in function `UnlockWardrobe'
> [string "@Interface/AddOns/ClickMorph/Live/Wardrobe.lua"]:133: in function <Interface/AddOns/ClickMorph/Live/Wardrobe.lua:131>
> 
> Locals:

**Comment by Ketho** [comment]
I don't use clickmorph anymore but I'll see if I can fix it up sometime after the holidays
